.PHONY: clean All

All:
	@echo "----------Building project:[ Singly-ll - Debug ]----------"
	@cd "Singly-ll" && "$(MAKE)" -f  "Singly-ll.mk"
clean:
	@echo "----------Cleaning project:[ Singly-ll - Debug ]----------"
	@cd "Singly-ll" && "$(MAKE)" -f  "Singly-ll.mk" clean
